### PR TITLE
Modified planimetry A5-0 + Added planimetries A6-1, A6-0, A6--1

### PR DESCRIPTION
**Pull request by madeincima**

### CODE REVIEW

**Comment by Piiit** [comment]
@sseppi Merged, please check the planimetry... maybe we need to find someone to have the know how to check these...

In addition the REUSE license checks fail, that needs to be fixed in another PR

**Comment by sseppi** [comment]
Hi @Piiit ,
> @sseppi Merged, please check the planimetry... maybe we need to find someone which has the know how to check these...

I already asked to Lukas to check 

> In addition the REUSE license checks fail, that needs to be fixed in another PR

This should be fixed by Cima?

**Comment by Piiit** [comment]
@sseppi we fixed the REUSE part, I merge everything and put it into production... please test

**Comment by sseppi** [comment]
@Piiit I will let Lukas Nagler know that he can test everything.

**Pull request merged**
