### PR TITLE
Synch between noi-techpark / webcomp-maps-noi and madeincima / webcomp-maps-noi

### PR DESCRIPTION
**Pull request by madeincima**
modified:   package-lock.json (was modified trying new modules - maybe could be gitignored?)
modified:   wcs-manifest.json (your edits like "key": "fullview", ...)
modified:   webpack.dev.js (removed unnecessary watch: true )
modified:   work/index.html (your edits <script src='noi_maps_widget.min.js'></script> and <map-view language="it" totem="0" fullview="1" hidezoom="0"></map-view>)

### CODE REVIEW

**Comment by Piiit** [comment]
@madeincima Have you forgotten to push something? I see 0 files changed...

**Comment by Piiit** [comment]
@madeincima That is possible, for example, if you change something, and then you change it back... you have 2 commits with diffs, but at the end 0 files changed.

**Comment by madeincima** [comment]
@Piiit Ok! So I think everything's ok, we finally synched the 2 repos (NOI vs MIC): I've probably made the same edits that my colleague Milena has already made :-) sorry for the trouble, now we are all synched

**Comment by Piiit** [comment]
OK, so then I close this PR without further actions... no problem

**Pull request closed without merging**
