### PR TITLE
New A2 -1 floor planimetry + fixes tooltip/icons position for the new rooms

### PR DESCRIPTION
**Pull request by madeincima**

### CODE REVIEW

**Comment by Piiit** [comment]
@madeincima Please rebase this PR on top of latest changes... This PR removes previous commits and fixes otherwise. Thank you!

**Comment by madeincima** [comment]
- the differences in the svg are only in the code, they aren't visual changes (we've added some hidden elements and changed classes)
- we've rebased let us know if it is ok now

**Comment by Piiit** [comment]
Thx

**Comment by lukasnagler** [comment]
@Piiit : MadeInCima merges the rooms according to my screenshot: 
Mummy

**Comment by Piiit** [comment]
@lukasnagler Understood, please open a new issue for that, so we can assign it to @madeincima ... Thank you

**Pull request closed without merging**
